FilmsCatalog/Models/ErrorViewModel.cs
using System;

namespace FilmsCatalog.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FilmsCatalog/Models/SignInViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace FilmsCatalog.Models
{
    public class SignInViewModel
    {
        [Required(ErrorMessage = "Обязательное поле")]
        [Display(Name = "Email")]
        public string Email { get; set; }
        
        [Required(ErrorMessage = "Обязательное поле")]
        [DataType(DataType.Password)]
        [Display(Name = "Пароль")]
        public string Password { get; set; }
        
        [Display(Name = "Запомнить?")]
        public bool RememberMe { get; set; }
        
        public string ReturnUrl { get; set; }
    }
}

FilmsCatalog/Models/SignUpViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace FilmsCatalog.Models
{
    public class SignUpViewModel
    {
        // [Required(ErrorMessage = "Обязательное поле")]
        [EmailAddress(ErrorMessage = "Необходимо указать корректный email")]
        // [DataType(DataType.EmailAddress)]
        [Display(Name = "Email*")]
        public string Email { get; set; }
        
        [Required(ErrorMessage = "Обязательное поле")]
        [Display(Name = "Имя*")]
        public string FirstName { get; set; }
        
        [Display(Name = "Фамилия")]
        public string LastName { get; set; }
        
        [Display(Name = "Отчество")]
        public string MiddleName { get; set; }
        
        [Required(ErrorMessage = "Обязательное поле")]
        [DataType(DataType.Password)]
        [Display(Name = "Пароль*")]
        public string Password { get; set; }
        
        [Required(ErrorMessage = "Обязательное поле")]
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "Пароли не совпадают")]
        [Display(Name = "Подтвердить пароль*")]
        public string PasswordConfirm { get; set; }
    }
}

FilmsCatalog/Controllers/AccountController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Logging;

using FilmsCatalog.Domain.Aggregates.UserEntities;
using FilmsCatalog.Models;

namespace FilmsCatalog.Controllers
{
    public class AccountController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly SignInManager<User> _signInManager;
        private readonly ILogger<AccountController> _logger;

        public AccountController(UserManager<User> userManager, SignInManager<User> signInManager,
            ILogger<AccountController> logger)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;
        }

        [HttpGet]
        public IActionResult SignUp()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SignUp(SignUpViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            
            var user = new User
            {
                Email = model.Email,
                UserName = model.Email,
                FirstName = model.FirstName,
                LastName = model.LastName,
                MiddleName = model.MiddleName
            };
            
            var created = await _userManager.CreateAsync(user, model.Password);
            if (created.Succeeded)
            {
                await _signInManager.SignInAsync(user, false);
                _logger.LogInformation("User success signup!");
                
                return RedirectToAction("Index", "Home");
            }

            foreach (var error in created.Errors)
            {
                _logger.LogError("User don't signup!");
                ModelState.AddModelError(String.Empty, error.Description);
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult SignIn(string returnUrl = null)
        {
            return View(new SignInViewModel {ReturnUrl = returnUrl});
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SignIn(SignInViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var signIn = await _signInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, false);
            if (!signIn.Succeeded)
            {
                ModelState.AddModelError(string.Empty, "Неверный логин или пароль");

                return View(model);
            }

            if (!string.IsNullOrEmpty(model.ReturnUrl) && Url.IsLocalUrl(model.ReturnUrl))
            {
                return Redirect(model.ReturnUrl);
            }

            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Logout()
        {
            await _signInManager.SignOutAsync();

            return RedirectToAction("Index", "Home");
        }
    }
}

FilmsCatalog/Controllers/FilmController.cs
using System;
using System.IO;
using System.Threading.Tasks;
using FilmsCatalog.Domain.Models.Dtos.FilmDtos;
using FilmsCatalog.Domain.Services.Interfaces;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;

namespace FilmsCatalog.Controllers
{
    public class FilmController : Controller
    {
        private readonly IFilmService _filmService;
        private readonly IWebHostEnvironment _appEnvironment;

        public FilmController(IFilmService filmService, IWebHostEnvironment appEnvironment)
        {
            _filmService = filmService ?? throw new ArgumentNullException(nameof(filmService));
            _appEnvironment = appEnvironment;
        }

        [HttpGet]
        [Route("Film/")]
        public async Task<IActionResult> Index()
        {
            var films  = await _filmService.GetFilmListAsync();
            
            return View(films);
        }
            
        [Route("Film/Create")]
        public IActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// Добавление нового фильма
        /// </summary>
        [HttpPost]
        public async Task<IActionResult> CreateFilmAsync(FilmDto filmDto)
        {
            var path = _appEnvironment.WebRootPath + "/" + filmDto.PosterImage.FileName;
            filmDto.PosterPath = path;
            
            await _filmService.CreateFilmAsync(filmDto);

            return Redirect("Film/");
        }
    }
}

FilmsCatalog/Controllers/HomeController.cs
using FilmsCatalog.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace FilmsCatalog.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FilmsCatalog/Views/Film/Create.cshtml
@model FilmsCatalog.Domain.Models.Dtos.FilmDtos.FilmDto
@{
    ViewData["Title"] = "Создание фильма";
}

<h2>Добавление фильма</h2>

<form asp-controller="Film" asp-action="CreateFilm"  method="post" enctype="multipart/form-data" style="margin-top: 2em;">
    <div class="form-row">
        <div class="form-group col-md-5 col-sm-6 col-12">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control">
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-10 col-sm-6 col-12">
            <label asp-for="Description"></label>
            <textarea class="form-control" name="Description" rows="5"></textarea>
        </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-5 col-sm-6 col-12">
            <label asp-for="Producer"></label>
            <input asp-for="Producer" class="form-control">
        </div>
    </div>
    <div class="form-row">
       <div class="form-group col-md-5 col-sm-6 col-12">
           <label asp-for="ReleaseYear"></label>
           <input class="form-control" name="ReleaseYear" type="number" rows="2">
           <span asp-validation-for="ReleaseYear" class="text-danger"></span>
       </div>
    </div>
    <div class="form-row">
        <div class="form-group col-md-5 col-sm-6 col-12">
            <label asp-for="@Model.PosterImage"></label>
            <input type="file" class="form-control-file" name="PosterImage">
        </div>
    </div>
    <div class="form-group">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <button type="submit" class="btn btn-outline-primary">Сохранить</button>
    </div>
</form>

FilmsCatalog/Views/Film/Index.cshtml
@model List<FilmsCatalog.Domain.Models.Dtos.FilmDtos.FilmDto>
@{
    ViewData["Title"] = "Фильмы";
}

@foreach (var film in Model)
{
    <div class="card mb-3">
        <img src="@film.PosterPath" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">@film.Name</h5>
            <p class="card-text">@film.Description</p>
            <p class="card-text">@film.Producer</p>
            <p class="card-text">@film.ReleaseYear</p>
            <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
        </div>
    </div>
}

FilmsCatalog/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

FilmsCatalog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Каталог фильмов</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Каталог фильмов</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - Каталог фильмов
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>